### PR TITLE
Canvas_coords: minor refactoring and add getEdgeCoords method

### PR DESCRIPTION
**Pull request by JadenJSPark**
fix some comments and add new util method
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by hunkim98** [comment]
이 브랜치는 동주작업을 merge할 때 고려하는 걸로 하면 될듯 (minor하기 때문에 merge 안해도 될듯)

**Comment by JadenJSPark** [comment]
그럼 동주 브랜치로 pr 날릴까요?

**Comment by hunkim98** [comment]
넵 그게 좋을 것 같습니다

**Comment by JadenJSPark** [comment]
closing as this has been implicitly merged with dongjoocha's recent pull request

**Pull request closed without merging**
