### PR TITLE
Implement graph visualization

### PR DESCRIPTION
**Pull request by dongjoocha**
Implemented friend(chon) graph visualization

## Description

- Each user node is a circle-shaped(including border) consisting of user image
- Graph shape depends on the number of one-chons and two-chons(maintain balanced, good-looking shape through mathematical calculation pre-implemented by @JadenJSPark)
- One-chon nodes are connected to the current user by solid lines, while two-chon nodes are connected to one-chon nodes by dotted lines
- Scaling for high resolution displays through calculation with DPR(Device Pixel Ratio)
- Panning and Zooming is pre-implemented by (@hunkim98)

## Related Issue

#17 

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by notiona — APPROVED** [review]
LGTM

**Comment by JadenJSPark** [comment]
`Canvas.ts` line 45에 `private chonNodes?: OneChonNode[];`에서 `chonNodes`가 empty array 일수도 있어서 ?가 붙은건가요?

**Review by hunkim98 — APPROVED** [review]
고생하셨습니다

**Comment by dongjoocha** [comment]
> `Canvas.ts` line 45에 `private chonNodes?: OneChonNode[];`에서 `chonNodes`가 empty array 일수도 있어서 ?가 붙은건가요?

네 맞습니다.

**Review by JadenJSPark — APPROVED** [review]
좋아요

**Pull request merged**
